name: sombra-cli CI

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  GO_VERSION: '1.23'
  PY_VERSION: '3.x'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Install dependencies
        run: go mod tidy

      - name: Run Go tests
        run: make test

      - name: Check import rules
        run: make imports

  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PY_VERSION }}

      - name: Validate docs
        run: make build-docs
