imports-checks:
  # NOTE: for some reason, `prefix` is not working in rules

  - folder: cmd/sombra
    rules:
      - allow:
          # stdlib
          - errors
          - os

          # 3rd party
          - github.com/alexflint/go-arg

          # sombra
          - github.com/sombrahq/sombra-cli/internal/runtime
          - github.com/sombrahq/sombra-cli/internal/frameworks/logger


  - folder: internal/core/entities
    exclude:
      - ".*_test\\.go"
    rules:
      - allow:
          # stdlib
          # these are necessary for type conversion
          - fmt
          - strings

  - folder: internal/core/usecases
    exclude:
      - ".*_test\\.go"
    rules:
      - allow:
          # stdlib
          - fmt
          - sort

          # (°o°)
          # TODO: move these deps to framework by means of ports
          - path/filepath
          - bytes
          - regexp

          # sombra
          - github.com/sombrahq/sombra-cli/internal/core/entities

  - folder: internal/frameworks/*
    rules:
      - allow:
          # stdlib
          - fmt
          - strings
          - bufio
          - os
          - os/exec
          - path/filepath
          - regexp
          - sort
          - sync
          - bytes
          - time
          - io
          - text/template

          # 3rd party
          - github.com/bmatcuk/doublestar/v4
          - github.com/google/uuid
          - github.com/rs/zerolog
          - github.com/rs/zerolog/*
          - gopkg.in/yaml.v3
          - github.com/Masterminds/sprig/v3
          - github.com/Masterminds/semver/v3

          # sombra
          - github.com/sombrahq/sombra-cli/internal/core/entities
          - github.com/sombrahq/sombra-cli/internal/core/usecases
          # the only packages allowed to import from framework packages
          - github.com/sombrahq/sombra-cli/internal/frameworks/logger
          # CVS Service must import specific ones
          - github.com/sombrahq/sombra-cli/internal/frameworks/cvs/*



  - folder: internal/frameworks/cvs/*
    rules:
      - allow:
          # stdlib
          - bytes
          - fmt
          - os
          - os/exec
          - path/filepath
          - strings

          # 3rd party
          - github.com/google/uuid

          # sombra
          - github.com/sombrahq/sombra-cli/internal/core/entities
          - github.com/sombrahq/sombra-cli/internal/core/usecases
          - github.com/sombrahq/sombra-cli/internal/frameworks/logger


  - folder: internal/runtime
    rules:
      - allow:
          # stdlib
          - fmt

          # 3rd party


          # sombra
          - github.com/sombrahq/sombra-cli/internal/core/entities
          - github.com/sombrahq/sombra-cli/internal/core/usecases
          - github.com/sombrahq/sombra-cli/internal/frameworks/*
